//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> TicketNumber { get; set; }
        public Nullable<int> TechID { get; set; }
        public Nullable<int> OldTicketNumber { get; set; }
    }
}
