//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int RecID { get; set; }
        public Nullable<int> TicketNo { get; set; }
        public string Initiator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<System.DateTime> ModTime { get; set; }
        public string Creator { get; set; }
        public string CSR { get; set; }
        public string Area { get; set; }
        public string First { get; set; }
        public string Middle { get; set; }
        public string Last { get; set; }
        public string Email { get; set; }
        public string Dept { get; set; }
        public string Phone { get; set; }
        public string OfficeLoc { get; set; }
        public string Priority { get; set; }
        public string BYUNo { get; set; }
        public string SerialNo { get; set; }
        public string EquipDesc { get; set; }
        public string EquipAffect { get; set; }
        public string ProblemDesc { get; set; }
        public string ProblemType { get; set; }
        public string ActNeed { get; set; }
        public string EquipLoc { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string TimeSpent { get; set; }
        public string Status { get; set; }
    }
}
