//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsForToday
    {
        public int TicketNumber { get; set; }
        public string Site { get; set; }
        public string TroubleUser { get; set; }
        public string Location { get; set; }
        public string Equipment { get; set; }
        public string Issue { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> TechID { get; set; }
        public Nullable<bool> Nutrition { get; set; }
        public string Day1 { get; set; }
        public string Day2 { get; set; }
        public string Day3 { get; set; }
        public string Day4 { get; set; }
        public string Day5 { get; set; }
    }
}
